export const TRANSITION_DURATION_LONG = 250;

export const COMPONENTS_SPACING = 40;
export const COMPONENTS_SPACING_MOBILE = 20;

export const BOARD_CELL_BORDER_WIDTH = 1;
export const BOARD_TILE_FONT_SIZE_MIN = 14;
export const BOARD_TILE_FONT_SIZE_POINTS_MIN = 10;
export const BOARD_TILE_SIZE_MAX = 64;
export const BOARD_TILE_SIZE_MIN = 32;

export const PLAIN_TILES_COLOR_DEFAULT = '#669933';
export const PLAIN_TILES_PADDING_HORIZONTAL = 0;
export const PLAIN_TILES_PADDING_VERTICAL = 0;
export const PLAIN_TILES_TILE_MARGIN = 6;
export const PLAIN_TILES_TILE_SIZE = 80;
