export type Comparator<T> = (a: T, B: T) => number;

export type Direction = 'horizontal' | 'vertical';

export type TranslationKey =
  | 'about'
  | 'achievements'
  | 'againstBots'
  | 'againstHumans'
  | 'cell.toggle-direction'
  | 'common.bot-game'
  | 'common.clear'
  | 'common.close'
  | 'common.concede'
  | 'common.exchange'
  | 'common.human-game'
  | 'common.loading'
  | 'common.points'
  | 'common.shuffle'
  | 'common.tiles'
  | 'common.word'
  | 'common.words'
  | 'dictionary.empty-state.no-definitions'
  | 'dictionary.empty-state.no-results'
  | 'dictionary.empty-state.not-allowed'
  | 'dictionary.empty-state.uninitialized'
  | 'dictionary.input.placeholder'
  | 'empty-state.error'
  | 'empty-state.info'
  | 'empty-state.success'
  | 'empty-state.warning'
  | 'existingOpponent'
  | 'github'
  | 'help'
  | 'invitations'
  | 'keyMap'
  | 'keyMap.board'
  | 'keyMap.board.toggle-direction'
  | 'keyMap.board-and-rack'
  | 'keyMap.board-and-rack.navigate'
  | 'keyMap.board-and-rack.remove-tile'
  | 'keyMap.board-and-rack.submit'
  | 'keyMap.rack'
  | 'newOpponent'
  | 'profile'
  | 'rack.placeholder'
  | 'remaining-tiles'
  | 'results.empty-state.no-filtered-results'
  | 'results.empty-state.no-results'
  | 'results.empty-state.outdated'
  | 'results.empty-state.uninitialized'
  | 'results.input.placeholder'
  | 'results.solve'
  | 'settings'
  | 'settings.bot'
  | 'settings.language'
  | 'singlePlayerGame'
  | 'statistics'
  | 'twoPlayerGame'
  | 'username'
  | 'words'
  | 'words.invalid'
  | 'words.valid';

export type Translate = (key: TranslationKey) => string;

export type Translations = Record<TranslationKey, string>;
